### ISSUE TITLE
Ошибка при попытке загрузить последнюю версию

### ISSUE THREAD

**Issue by sesm** [ExtraDJ/joyreactor_visitor#1]
<img width="659" alt="Screenshot 2022-08-18 at 16 45 50" src="https://user-images.githubusercontent.com/1313744/185410665-6171b81d-0463-42b3-a0bf-51b6567bae9e.png">

Воспроизводится в Chromium и Vivaldi. В Chrome всё нормально

**Comment by sesm** [comment]
Ошибка возникает в Chrome и всех браузерах на основе Chromium, потому что service worker лежит не в той же директории что `manifest.json`. Держать его в другой директории можно только начиная с Chromium 93: https://chromiumdash.appspot.com/commit/98c063ae403b2a03c75881523381e468da4c542b

Можно либо перенести service worker в другую директорию, либо обозначить что расширение только для Chrome/Chromium 93 и выше

**Comment by ExtraDJ** [comment]
Исправлено 0.9.0
