### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by sesm** [ExtraDJ/joyreactor_visitor#2]
Шаги воспроизведения:
- Устанавливаем расширение
- Нажимаем на появившуюся кнопку в панели
- Появляется ошибка `Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.` от этой строчки: https://github.com/ExtraDJ/joyreactor_visitor/blob/250a3580679928180be40b1a87c284f43b94f9dc/src/data/js/script.js#L164

Воспроизводится в Chrome 104.0.5112.79 и Vivaldi 5.4.2753.37 (на основе 104.0.5112.105) на MacOS

**Comment by ExtraDJ** [comment]
Исправлено для версии 1.0+
